name: Build APK on Release

on:
  release:
    types: [created] # Déclenche uniquement lors de la création d'une release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # ou la version de Node.js que vous utilisez

      - name: Install dependencies
        run: npm install

      - name: Build APK
        run: |
          npm install -g expo-cli
          expo build:android --no-publish --release-channel ${{ github.event.release.tag_name }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app.apk
          path: ./android/app/build/outputs/apk/release/app-release.apk # Chemin vers l'APK généré

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ./android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}